#!/bin/sh
pushd ~/.dotfiles
git add --intent-to-add .
#sudo nixos-rebuild switch --flake .?submodules=1# --show-trace
#sudo nixos-rebuild switch --flake path://$(pwd)# --show-trace --builders ""
sudo -v
#sudo nixos-rebuild switch --flake .?submodules=1# --show-trace --builders "" --log-format internal-json -v |& nom --json
nh os switch .?submodules=1
#sudo nixos-rebuild switch --flake .?submodules=1# --show-trace --log-format internal-json -v |& nom --json
#sudo nixos-rebuild switch --flake path://$(pwd)# --show-trace --builders "" --log-format internal-json -v
#sudo nixos-rebuild switch --flake path://$(pwd)# --show-trace
#hyprctl reload
popd
