#!/bin/sh
set -x
pushd ~/.dotfiles
pushd secrets
git add .
popd
name=$1
shift
# deploy .?submodules=1#$name --remote-build -s $@ -- --show-trace --no-warn-dirty -j 0  --log-format internal-json -v |& nom --json
# deploy .?submodules=1#$name --remote-build -s $@ -- --show-trace --no-warn-dirty -j 0 
deploy .?submodules=1#$name -s --magic-rollback false --auto-rollback false -- $@ --show-trace --no-warn-dirty  --impure --log-format internal-json |& nom --json
# deploy .?submodules=1#$name -s $@ -- --show-trace --no-warn-dirty  --impure  --log-format internal-json -v |& nom --json
# deploy .?submodules=1#$name -s $@ -- --show-trace --no-warn-dirty -j 0  --log-format internal-json -v |& nom --json
# deploy .?submodules=1#$1 -s  -- --show-trace --no-warn-dirty
popd
