#!/bin/sh
set -x
pushd ~/.dotfiles
pushd secrets
git add .
popd
name=$1
shift
deploy .?submodules=1#$name -s $@ -- --show-trace --no-warn-dirty --log-format internal-json -v |& nom --json
#deploy .?submodules=1#$1 -s  -- --show-trace --no-warn-dirty
popd
