#!/bin/sh
pushd ~/.dotfiles
pushd secrets
git add .
popd
deploy .?submodules=1#$1 -s  -- --show-trace --no-warn-dirty --log-format internal-json -v |& nom --json
#deploy .?submodules=1#$1 -s  -- --show-trace --no-warn-dirty
popd
